tap 'homebrew/cask-fonts'
tap 'railwaycat/emacsmacport'

brew 'bat'
brew 'colordiff'
brew 'coreutils'
brew 'exa'
brew 'ghq'
brew 'git'
brew 'gnu-sed'
brew 'gnu-tar'
brew 'go'
brew 'golangci-lint'
brew 'grep'
brew 'hub'
brew 'jq'
brew 'kubectx'
brew 'kubernetes-cli'
brew 'make'
brew 'mas'
brew 'peco'
brew 'starship'
brew 'stern'
brew 'tmux'
brew 'wget'
brew 'zsh'

cask 'adobe-creative-cloud'
cask 'atok'
cask 'blackhole-16ch'
cask 'blackhole-2ch'
cask 'docker'
cask 'dropbox'
cask 'emacs-mac'
cask 'firefox'
cask 'font-fontawesome'
cask 'font-hack-nerd-font'
cask 'hyper'
cask 'karabiner-elements'
cask 'macs-fan-controll'
cask 'slack'
cask 'steam'

mas 'LINE', id: 539883307
